### ISSUE TITLE
Tshirts for HRDevFest

### ISSUE THREAD

**Issue by privette** [RevolutionVA/slackin#3]
- [ ] Get logos for tshirts

- [ ] get designs 

- [ ] get pricing

- [ ] contact PrinceInk

**Comment by iamerikjolson** [comment]
done

![screen_shot_2017-11-06_at_8 12 37_am](https://user-images.githubusercontent.com/1593872/32445645-608cb834-c2d4-11e7-89b2-63a6ab04a1ea.png)
